services:
  robin-mta:
    container_name: robin-mta
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./cfg:/usr/local/robin/cfg
      - ./log:/var/log
      - ./store:/usr/local/robin/store
    ports:
      - "25:25"     # SMTP
      - "587:587"   # SUBMISSION
      - "465:465"   # SMTPS
      - "8080:8080"   # Metrics
      - "8090:8090"   # API
